### ISSUE TITLE
How can we obtain the index cells?

### ISSUE THREAD

**Issue by alexandruioanvoda** [iaconogi/bigSCale2#1]
Hi!

I couldn't figure out from the tutorial (which ran just fine) how to extract the expression matrix of the index cells (analogous to extracting the single-cell expression matrix with `assay(sce)`). Could someone please give any pointers?

**Comment by iaconogi** [comment]
Dear Alexandru,
I realize this is the same issue we solved by mail, correct?
Best
Giovanni

**Comment by alexandruioanvoda** [comment]
Yes, I was asking about iCell before the feature was released.
