### ISSUE TITLE
0 nodes and 0 edges after GO filtering

### ISSUE THREAD

**Issue by bharati-mehani** [iaconogi/bigSCale2#11]
Just to give a brief background, I am using SmatSeq2 scRNA Seq data having 25 bp PE reads. I want to use Networks tool from bigSCale2. For which, I used direct mode with compute.network.
This led to identify 13617 nodes and 189399 edges in my raw regulatory network. But after GO filtering it gives 0 nodes and 0 edges, as shown below:

"Inferred the raw regulatory network: 13617 nodes and 189399 edges (ratio E/N)=13.909011"
[1] "Recognized 0/0 (NaN%) as Human, Gene Symbol"
[2] "Recognized 0/0 (NaN%) as Human, ENSEMBL"    
[3] "Recognized 0/0 (NaN%) as Mouse, Gene Symbol"
[4] "Recognized 0/0 (NaN%) as Mouse, ENSEMBL"    

[1] "Final network after GO filtering: 0 nodes and 0 edges (ratio E/N)=NaN and 0 components"

I am worried if it is because any of these networks are not significant enough as per the default parameters. Or is there any possibility that the tool could not compare my list of candidate genes from the network with the GO database.

Looking for your kind help and guidance.

Thanks

**Comment by JasonLiZhou** [comment]
Which type of gene ID did you use? I wonder if you used ensembl id that have a numeric postfix (e.g. ENSMUSG00000102693.1), which may not be recognized by the database.

**Comment by bharati-mehani** [comment]
I am using HGNC gene ids.

**Comment by JasonLiZhou** [comment]
No wonder, according to the 'Readme.md' instruction, only gene symbol or esenmbl is supported at the moment.
![gene_name](https://user-images.githubusercontent.com/11907573/61025898-a6ee0b00-a3e4-11e9-9c4d-10eb533bc699.png)

**Comment by iaconogi** [comment]
Thanks for pointg that out JasonLiZhou , that is in fact the reason!
