### ISSUE TITLE
Analyzing 10X single cell data for regulatory network

### ISSUE THREAD

**Issue by bharati-mehani** [iaconogi/bigSCale2#12]
Hi Giovanni,
This could be a naive question but I am a bit confused.
I want to analyse 10X single cell RNA data in order to explore the regulatory network. In this case, the data has a cumulative reads from all the cells for a sample. 

For analyzing regulatory network using bigSCale2, I believe it requires demultiplexed read counts from each cell. If this is the case, can you please tell how should I demultiplex my cumulative fastq files to cell specific fastq or cumulative read counts to cell specific read count for each sample.

Thanks

**Comment by bharati-mehani** [comment]
Resolved this issue by calculating reads per barcode.

Thanks

**Comment by iaconogi** [comment]
In fact I wanted to tell you that you should use CellRanger to get the expression counts.
Glad that you figured it out sooner.
Best
Giovanni
