### ISSUE TITLE
bigSCale2 considers data only from 5000 cells 

### ISSUE THREAD

**Issue by bharati-mehani** [iaconogi/bigSCale2#13]
[1] "Pre-processing) Removing null rows "
[1] "Discarding 20 genes with all zero values"
[1] "PASSAGE 1) Setting the size factors ...."
[1] "PASSAGE 2) Setting the bins for the expression data ...."
[1] "97.0 % of elements < 10 counts, therefore Using a UMIs compatible binning"[1] "PASSAGE 3) Storing in the single cell object the Normalized data ...."
[1] "PASSAGE 4) Computing the numerical model (can take from a few minutes to 30 mins) ...."
**[1] 19369  5000**

Going through the given log file as highlighted above, I noticed that bigSCale2 considered only 5000 cells, though I parsed the data from 35639 cells. Thus, have few queries:
1. Does that mean, in order to analyze regulatory network using bigScale2 we should use cells from one sample at a time? 
2. Can't we merge all the cells from a group of samples to compare them with other? 
3. Does it pick top 5000 significant genes to derive their regulatory network? If it is so, how does it rank the genes?

**Comment by JasonLiZhou** [comment]
Hi, bharati16mehani. 
1&2. According to the source code, when your cell number is greater than 5000, a down-sampling will be performed, as mentioned in the function 'fit.model' (R-functions.R_line 3094). Therefore 5000 cells might be enough to compute the numerical model.
![fit model](https://user-images.githubusercontent.com/11907573/61354118-03996c00-a8a4-11e9-88b4-916aa9fcce21.png)
3. It's 5000 cells, not 5000 genes.

**Comment by bharati-mehani** [comment]
Hi JasonLiZhou,
In my 3rd point I also meant cells. Sorry for the typo.
Did you mean, even after pooling cells from multiple samples together down-sampled 5000 cells will be good enough to compute the numerical model?

Thanks for sharing the reference and explanation.

Bharati

**Comment by JasonLiZhou** [comment]
Yes, I think this might be what has been done during the numerical computation step for time saving. Meanwhile I think the algorithm recognizes the input as an expression matrix consisting of m genes and n cells (no matter of pooling samples or not).

**Comment by bharati-mehani** [comment]
Thanks

**Comment by iaconogi** [comment]
Dear bharati16mehani,
5000 cells are a random subset of cells which are normally more than enough to compute the numerical model, later used for clustering and DE.
All the subsequent analysis use all the cells of your dataset. 

P.S. If you want to check if the numerical model looks allright the tutorial explains how to do.

Best
Giovanni
