### ISSUE TITLE
Object 'out' not found when tweaking previous network

### ISSUE THREAD

**Issue by JasonLiZhou** [iaconogi/bigSCale2#16]
Dear Giovanni,
When I tried to tweak previous network with 'compute.network' , there came an error, as shown below:

> `ctl.grn <- compute.network(previous.output = ctl.grn, quantile.p = 0.999)`
> [1] "It appears you want to tweak previously created networks with a different quantile.p, proceeding ...."
> Error in compute.network(previous.output = ctl.grn, quantile.p = 0.999) : 
>   object 'out' not found
> In addition: Warning message:
> In if (is.na(previous.output)) { :
>   the condition has length > 1 and only the first element will be used

Then I searched the source code, it seems that the parameter 'out' is not defined

> ![bigscale_tweak](https://user-images.githubusercontent.com/11907573/61780250-c64d5500-ae34-11e9-9a87-bbf6c5611543.png)

Looking for your help.
Thanks,
Jason

**Comment by iaconogi** [comment]
Dear Jason I will try to fix it tomorrow

**Comment by iaconogi** [comment]
It should be fixed now
