### ISSUE TITLE
Critical value way too high (1.02513e+10): Stopping the analysis while performing compute.distance under compute.network

### ISSUE THREAD

**Issue by bharati-mehani** [iaconogi/bigSCale2#21]
While performing compute.network(), I am getting following error: 

Recursive clustering, beginning round 1 ....[1] "Analyzing 3622 cells for ODgenes, min_ODscore=2.33"
[1] "Proceeding to calculated cell-cell distances with bigscale modality"
Error in compute.distances(expr.norm = expr.data.norm[, which(mycl ==  : 
  Critical value way too high (1.02513e+10): Stopping the analysis!!
Calls: compute.network -> bigscale.recursive.clustering -> compute.distances
In addition: Warning messages:
1: 'Rfast::sort_mat' is deprecated.
Use 'Rfast::rowSort' instead.
See help("Deprecated") 
2: In compute.distances(expr.norm = expr.data.norm[, which(mycl ==  :
  Critical value very high (1.02513e+10): Increased memory usage!!
Execution halted

**Comment by wangx3385** [comment]
when I performed the first step bigscale(sce), I got an error:
[1] "Computing the pseudotime ..."
[1] "Searching for tail clusters ..."
[1] "Computing distances of 0 tail clusters ..."
Error in end.tails[[k]] : subscript out of bounds
In addition: Warning message:
In compute.distances(expr.norm = normcounts(object), N_pct = object@int_metadata$model,  :
  Critical value very high (316771): Increased memory usage!!

can you help me figure out this error? thanks!
