### ISSUE TITLE
Using a singleCellExperiment type object converted from a Seurat type causes bigscale() to error out.

### ISSUE THREAD

**Issue by eregenyi** [iaconogi/bigSCale2#22]
Hi,
I was using Seurat, and did some QC and filtering on my SC data. Then converted it with as.SingleCellExperiment(), to be able to use bigSCale. However, when applying the bigscale() function, it throws me an error after running just fine for quite some time. The error occurs at passage 10, and reads the following:

`[1] "PASSAGE 10) Computing the markers (slowest part) ..."`

`Error in print.default() : argument "x" is missing, with no default`

I am guessing there is an issue with one of the messages that is supposed to be printed, but I don't know why. 
What could be the issue?

Thanks for any help in advance

**Comment by iaconogi** [comment]
Dear eregenyi,
thanks for your interest in bigSCale2.
I will look into the issue ASAP.
Also, It would greatly help if you could send a sample of the object generating the issue.

**Comment by iaconogi** [comment]
I did not hear back from you so I am closing the issue.
Feel free to contact me again if you need.
Best

**Comment by eregenyi** [comment]
Hi iaconogi, 

I apologize for the delayed reply. I tried to replicate the error with a publicly available data set on my home PC, but the conversion worked, no errors were thrown. At my workplace the tool is now installed in its own miniconda environment, and it seems to work fine. My guess is that it could have been some weird installation problem, not sure what exactly.

Best
