### ISSUE TITLE
Network using non-Ensembl/-symbol gene names

### ISSUE THREAD

**Issue by pburnham50** [iaconogi/bigSCale2#23]
I was wondering if there was any way around filtering genes based on their names in the network algorithm. If I understand correctly from your paper, you filter the correlation network based on gene ontology? Right now I am using modified Ensembl IDs for the gene names and as a result the graph is empty.

**Comment by iaconogi** [comment]
Yes the network is polished using the gene ontology.
You can use also Official Gene Symbols instead of Ensembl IDs.

**Comment by iaconogi** [comment]
If you have further questions you can also contact me at gio.iacono.work@gmail.com

**Comment by pburnham50** [comment]
Thanks I'll contact your email. Great software!
