### ISSUE TITLE
Correlation matrix and the list of genes with centrality from bigSCale2

### ISSUE THREAD

**Issue by bharati-mehani** [iaconogi/bigSCale2#24]
Hi Giovanni,
It could be again a naive question but I wanted to ask why do we have different # of genes between the correlation matrix and the list of genes with centrality?
Would it be recommended to look for the overlapping genes between the above two list to find out any interesting observation?

Thanks

**Comment by iaconogi** [comment]
Dear Bharati,
sorry for coming back so late, but as it wasn't an urgent question....
Correlation matrix contains all the genes of the transcriptome. The genes included in the network (and therefore with centrality) are a subset of those.
I do not think there is anything interesting in comparing the two. The genes which are not in the network dimply did not pass enough cutoff filters. Yet if you are interested in them you can inspect their correlations in the correlation matrix.
