### ISSUE TITLE
Failed to install 'bigSCale'

### ISSUE THREAD

**Issue by MingwuDuan** [iaconogi/bigSCale2#25]
Hi everyone,

Eventually the installation was aborted, which made me sad. Logs and environment as follows.

> devtools::install_github("iaconogi/bigSCale2")
Downloading GitHub repo iaconogi/bigSCale2@master
Skipping 21 packages not available: Rcpp, SingleCellExperiment, Rfast, Rtsne, float, ggplot2, zoo, dendextend, BioQC, igraph, org.Hs.eg.db, org.Mm.eg.db, RgoogleMaps, ggbeeswarm, ggpubr, plotly, heatmap3, progress, bigmemory, R.utils, RJSONIO
√  checking for file 'C:\Users\xxx\AppData\Local\Temp\Rtmpc9Thpy\remotes4745885785f\iaconogi-bigSCale2-0b688ee/DESCRIPTION' (911ms)
> -  preparing 'bigSCale': (1.2s)
   checking DESCRIPTION meta-information ...
   checking DESCRIPTION meta-information ... 
√  checking DESCRIPTION meta-information
>-  cleaning src
>-  checking for LF line-endings in source and make files and shell scripts
>-  checking for empty or unneeded directories
>-  looking to see if a 'data/datalist' file should be added
   building 
>-  building 'bigSCale_1.7.tar.gz'
ERROR: dependencies 'SingleCellExperiment', 'Rfast', 'Rtsne', 'float', 'zoo', 'dendextend', 'BioQC', 'igraph', 'org.Hs.eg.db', 'org.Mm.eg.db', 'RgoogleMaps', 'ggbeeswarm', 'ggpubr', 'plotly', 'heatmap3', 'progress', 'bigmemory', 'R.utils', 'RJSONIO' are not available for package 'bigSCale'
>* removing 'C:/Program Files/R/R-3.6.1/library/bigSCale'
错误: Failed to install 'bigSCale' from GitHub:
  (由警告转换成)installation of package ‘C:/Users/xxx/AppData/Local/Temp/Rtmpc9Thpy/file47452de53ba/bigSCale_1.7.tar.gz’ had non-zero exit status

R version: 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
OS: Win7 x64 with sp1

Should I use Ubuntu?  Looking forward to any suggestions.

**Comment by iaconogi** [comment]
Dear MingwuDuan,
it appears that by running devtools::install_github("iaconogi/bigSCale2") none of the dependencies is automatically installed, which causes the error.
One solution which is slow but will work for sure is to install the dependencies manually (the 21 packages listed in the error).
So:
install.packages('Rcpp')
install.packages('Rfast')
ans so on.
Please note that some packages are from Bioconductor, so you'll need to install them like this:

BiocManager::install("SingleCellExperiment")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("org.Mm.eg.db")


Do not hesistate to contact me for further help.
Best
Giovanni
