### ISSUE TITLE
construct Gene Regulatory Networks for other species SC data

### ISSUE THREAD

**Issue by ChengTao2017** [iaconogi/bigSCale2#27]
Dear iaconogi,
Thanks for such nice tools!
I am wondering how to use bigSCale2 construct GRN for other species SC data(for example zebrafish)

**Comment by iaconogi** [comment]
Dear ChengTao2017,
I will try to include this feature ASAP.
I will let you know.
Best
Giovanni

**Comment by ChengTao2017** [comment]
Thanks!
