### ISSUE TITLE
Error at clustering stage

### ISSUE THREAD

**Issue by waseemabbas05** [iaconogi/bigSCale2#28]
I am applying bigScale to a unique dataset. The dataset contains single cell gene expression matrix, 9320 genes and 9120 cells.
Without any preprocessing whatsoever, I run bigScale on this dataset by first embedding it into SingleCellExperiment Class. It runs fine until clustering and I get this error
**Error in hclust(D, method = "ward.D") : 
  NA/NaN/Inf in foreign function call (arg 10)**
I even tried with custom hclust but the error persist
Any ideas?

**Comment by iaconogi** [comment]
Dear waseemabbas05, sorry for coming back so late to you, but for the coronavirus I had troubles working in the past two weeks. Do you still need help to solve the problem?
Best
Giovanni

**Comment by waseemabbas05** [comment]
Thank you for responding.
I still need an assist

**Comment by iaconogi** [comment]
Can you copy-paste the full on screen output and not just the last two lines?
Thank you very much!
