### ISSUE TITLE
Could bigscale2 export gene clusters or gene modules after analyzing  GRN?

### ISSUE THREAD

**Issue by zehualilab** [iaconogi/bigSCale2#29]
Thanks for the tools! 
I am wondering whether bigscale2 could  export gene clusters or gene modules after analyzing  GRN. 
Thanks a lot.

**Comment by iaconogi** [comment]
Hi,
bigSCale never computes gene clusters nor gene modules.
You can use the igraph tools over the graph created by bigSCale to do so.
For example igraph::cluster_louvain()

**Comment by zehualilab** [comment]
Thanks for help! I will try that!
