### ISSUE TITLE
viewSignatures-Error in x - a

### ISSUE THREAD

**Issue by bioguy2018** [iaconogi/bigSCale2#3]
Hi, I have converted my data from seurat object to a SCE class. After I ran the bigscale() command when I want to view my signature I get the following error regarding to the ggplot apparently

> Error in x - a : non-numeric argument to binary operator
In addition: Warning messages:
1: In cbind(palette, ColSideColors) :
  number of rows of result is not a multiple of vector length (arg 1)
2: In mean.default(x) : argument is not numeric or logical: returning NA
3: In mean.default(x) : argument is not numeric or logical: returning NA

I have no clue how can it happen and how should I resolve it. 

I would appreciate it any comment on it !

Thanks

**Comment by PGmajev** [comment]
Hello,

I have the same error, but different warning messages:
`Error in x - a : non-numeric argument to binary operator
In addition: Warning messages:
1: In mean.default(x) : argument is not numeric or logical: returning NA
2: In var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm) :
  NAs introduced by coercion
3: In mean.default(x) : argument is not numeric or logical: returning NA
4: In var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm) :
  NAs introduced by coercion`

I loaded Alevin results into a SingleCellExperiment Object and for all other Analyses (scran,scater, importing to Seurat) this works. Also the bigSCale command does not fail! Only the visualisation commands after that fail.

Any help would be highly appreciated!

**Comment by iaconogi** [comment]
Sorry I just saw your issues now. I apologize.
I'll work on that ASAP

**Comment by iaconogi** [comment]
Do you still have the problem with the latest version of today?
Best
Giovanni

**Comment by PGmajev** [comment]
Hi Giovanni,

thank you very much for the reply.

I have reinstalled the current Version of bigSCale by using `devtools::install_github("iaconogi/bigSCale2", force = TRUE)` I hope this was correct?

With this I still encounter the same error as before for my own dataset. 

With the test dataset (`data(sce)`) everything works as expected. How may I assist further in solving this?

**Comment by iaconogi** [comment]
Dear PGmajev,
It looks like to column data of your single cell object (ie. colData(object)) is in some format not handable by bigSCale2.
colData is supposed to be either numeric vectors or a factors.
One temporary solution is to remove colData from your object and then run ViewSignatures, that should work.
Also, It would be of great help to me if you could share with me your single cell object, maybe just a small chunk of some cells, so that I figure out what the exact problem is and correct bigSCale.

My e-mail is gio.iacono.work@gmail.com

Best
Giovanni

**Comment by iaconogi** [comment]
Dear PGmajev,
any update on your bug?
Best
Giovanni

**Comment by PGmajev** [comment]
Hi Giovanni,

I am cureently out of office, but will come back to this as soon as possible. Thanks for pushing to solve this issue!

Best

**Comment by GildasLepennetier** [comment]
Hi there.

For me this helped, thanks @iaconogi 

The commands, if anyone has the same problem, are:

```
DF=colData(sce)
DF_sub= DF[,c("integrated_snn_res.0.6", "group")] #select here some metadata
    #str(DF_sub) -> investigate to have only integer and factors
colData(sce) = DF_sub
```

It would be amazing to have a check for the coldata and have an error message if it is not as expected.
