### ISSUE TITLE
Bigscale Repo removed

### ISSUE THREAD

**Issue by rahulbhadani** [iaconogi/bigSCale2#30]
Dear @iaconogi

I am not sure what was the point of removing https://github.com/iaconogi/bigSCale when it is mentioned in the paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5991513/pdf/878.pdf

What happened to reproduciblity aspects of the paper and the reader who are going to read the paper and what to reproduce the result? I have web archive extension installed so I was able to see an archived version which navigated me to bigScale2, but not every reader are tech-savvy in this matter.

Can you please bring back bigScale repo?

Thanks.
Rahul

**Comment by iaconogi** [comment]
Dear user, 
unfortunately bigSCale2 is no longer maintained, as I now state in the ReadMe webpage. I leave the project to the community.
