### ISSUE TITLE
Error: vector memory exhausted (limit reached?)

### ISSUE THREAD

**Issue by skim245** [iaconogi/bigSCale2#31]
Thank you for developing this tool ! 
I'm trying to use bigSCale 2 Gene Regulatory Networks with big dataset 

"37625 features across 34419 samples"

and gets below error ! 

results.ctl=compute.network(expr.data = counts.data, gene.names = gene.names, clustering = "direct")
[1] "Pre-processing) Removing null rows "
Error: vector memory exhausted (limit reached?)
In addition: Warning message:
In compute.network(expr.data = counts.data, gene.names = gene.names,  :
  It seems you are running compute.network on a kind of large dataset, it it failed for memory issues you should try the compute.network for large datasets

are there anyways to bypass this memory issues? 

Thank you in advance!

**Comment by iaconogi** [comment]
Dear user, 
unfortunately bigSCale2 is no longer maintained, as I now state in the ReadMe webpage. I leave the project to the community.
