### ISSUE TITLE
How can I get the cell information after iCells() downsample process?

### ISSUE THREAD

**Issue by xujingmei111** [iaconogi/bigSCale2#32]
hi, I need get the cell information of the expression data,that is ,the column name of the expression data.
but,I read the source code and found that iCells() function input with the sparse matrix  which only contains the numeric data and  missing the column names,how can I get it ? Thanks~

**Comment by xujingmei111** [comment]
I think the first and second column  of out$iCells may  means pre and post cells index number.

**Comment by xujingmei111** [comment]
sorry ,the downsample cell expression count may not be the real sequecing data ,instead,it may be the simulated data or  feature-rebuild data.Does it right?

**Comment by iaconogi** [comment]
Dear user, 
unfortunately bigSCale2 is no longer maintained, as I now state in the ReadMe webpage. I leave the project to the community.
