### ISSUE TITLE
compute.network error "modality argument missing"

### ISSUE THREAD

**Issue by dpcook** [iaconogi/bigSCale2#5]
Hi @iaconogi,

I'm having a small issue with the compute.network function. When it gets to the recursive clustering in Round 5, it throws the error that the argument modality is missing with no default.

Looking into the source code, this seems to arise because the bigscale.recursive.clustering() function calls compute.distances(), but fails to set the modality argument that it requires.

David

**Comment by iaconogi** [comment]
Sry, it was a bug, now corrected in the update I did now.
Best
Giovanni

Il giorno gio 30 mag 2019 alle ore 16:51 David Cook <
notifications@github.com> ha scritto:

**Comment by dpcook** [comment]
Seems fixed now. Thanks Giovanni!
