### ISSUE TITLE
Input file format for bigSCale2

### ISSUE THREAD

**Issue by bharati-mehani** [iaconogi/bigSCale2#7]
How should we prepare the input file for bigSCale2

**Comment by iaconogi** [comment]
Dear bharati16mehani,
to answer I need to know:
1) What platform did you use to generate the data (10x, SmartSeq2)?
2) Wha tool of bigSCale framework do you need to use (Core, iCells or Networks) ?

**Comment by bharati-mehani** [comment]
Hi Admin, thank you for following up my query.

I am using SmarSeq2 data and planning to use Networks from bigSCale
framework.

Regards
Bharati

**Comment by iaconogi** [comment]
Dear bharati16mehani,
in this case it is enough to simply import the expression counts and gene names into R, with a command like read.table(). 
Next, you can run directly the line of the tutorial "compute.network(...)"
Contact me at gio.iacono.work@gmail.com if you need more explicit help.
Best
Giovanni

**Comment by bharati-mehani** [comment]
Thanks for the help.
