### ISSUE TITLE
compute.network error

### ISSUE THREAD

**Issue by bharati-mehani** [iaconogi/bigSCale2#9]
Hi I am getting error while performing compute.network during 
Recursive clustering, after round 6 obtained 11 clusters[1] "Calculating Zscores for 17726 genes expressed in at least 15 cells"

The error message I am getting is:

Error in bigscale.DE(expr.norm = expr.norm, N_pct = N_pct, edges = edges,  : 
  Critical value too high (1.58501e+06): Note from bigSCale author, you have to increase indA.size

How can I resolve this error? Any help will be highly appreciated.

Thanks

**Comment by iaconogi** [comment]
It seems you have some extreme values in your counts.
Before tweaking the source code, I want to assure that 

1) You are providing raw counts, not normalized in any way

2) You discarded low quality cells with few reads / detected genes. This is a easy step you can do by simply summing the values over the columns and discarding the lower tail.

Giovanni

**Comment by bharati-mehani** [comment]
Hi Giovanni,
Just to confirm, Yes I am using raw read counts and even after removing cells as well as genes with few reads. I am still getting the similar error as given below:

Recursive clustering, after round 6 obtained 10 clusters[1] "Calculating Zscores for 14233 genes expressed in at least 15 cells"
Error in bigscale.DE(expr.norm = expr.norm, N_pct = N_pct, edges = edges,  : 
  Critical value too high (292807): Note from bigSCale author, you have to increase indA.size
In addition: Warning messages:
1: In compute.distances(expr.norm = expr.data.norm[, which(mycl ==  :
  Critical value very high (1.3294e+06): Increased memory usage!!
2: In compute.distances(expr.norm = expr.data.norm[, which(mycl ==  :
  Critical value very high (137642): Increased memory usage!!
3: In compute.distances(expr.norm = expr.data.norm[, which(mycl ==  :
  Critical value very high (1.44178e+06): Increased memory usage!!
4: In compute.distances(expr.norm = expr.data.norm[, which(mycl ==  :
  Critical value very high (190921): Increased memory usage!!

I can run the above command with direct mode of clustering but could not with recursive mode. Is that something to do with memory usage and also not sure about indA parameter?

Looking for your help.
Thanks

**Comment by iaconogi** [comment]
Dear bharati16mehani,
direct mode does not use the indA parameter and that is why it works.
I will tweak the code to increase the maximum value of indA so you can you also recursive mode.
I'll let you know asap.
Best
Giovanni

**Comment by iaconogi** [comment]
Dear bharati16mehani,
I corrected the bug, now you should be able to run the tool also with mode='recursive'.

First you need to install it again from GitHub.

Contact me again if it gives the same mistake.
